name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: ls -a via ssh
      run: |
        pwd
        composer install
        sudo cp -R . /var/www/html/ 
        cd /var/www/html
        sudo chmod 775 storage
        sudo chmod 775 bootstrap/cache
        sudo cp .env.example .env
        php artisan key:generate
