name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: ls -a via ssh
      run: |
        pwd
        composer install
        cp -R * /var/www/html/ && cd /var/www/html
        chmod 775 storage
        chmod 775 bootstrap/cache
        cp .env.example .env
        php artisan key:generate
