name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 167.99.72.59
        paaswword : Azkal182AA
        script: 'pwd && apt update'
