name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: ls -a via ssh
      run: |
        pwd
        composer install
    - name: create .env and key generate
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan migrate
    - name: copy to server
      run: |
        sudo \cp -R . /home/server.rezaputra.site/server
        cd /home/server.rezaputra.site/server
    - name: change permission
      run: |
        sudo chmod 775 storage
        sudo chmod 775 bootstrap/cache
