name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: ls -a via ssh
      run: |
        pwd
        composer install
    - name: create .env and key generate
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: copy to html
      run: |
        sudo \cp -R . /var/www/html/ 
        cd /var/www/html
    - name: change permission
      run: |
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod 775 storage
        sudo chmod 775 bootstrap/cache
